/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'dt-bg': 'var(--dt-bg)',
        'dt-surface': 'var(--dt-surface)',
        'dt-card': 'var(--dt-card)',
        'dt-hover': 'var(--dt-hover)',
        'dt-border': 'var(--dt-border)',
        'dt-text': 'var(--dt-text)',
        'dt-text-2': 'var(--dt-text-2)',
        'dt-text-3': 'var(--dt-text-3)',
        'dt-primary': 'var(--dt-primary)',
        'dt-primary-dark': 'var(--dt-primary-dark)',
        'dt-primary-deeper': 'var(--dt-primary-deeper)',
        'dt-secondary': 'var(--dt-secondary)',
        'dt-tertiary': 'var(--dt-tertiary)',
        'dt-quaternary': 'var(--dt-quaternary)',
        'dt-success': 'var(--dt-success)',
        'dt-warning': 'var(--dt-warning)',
        'dt-error': 'var(--dt-error)',
        'dt-info': 'var(--dt-info)',
        'dt-type-bg': 'var(--dt-type-bg)',
        'dt-type-border': 'var(--dt-type-border)',
        'dt-type-pending': 'var(--dt-type-pending)',
        'dt-bronze-bg': 'var(--dt-bronze-bg)', 'dt-bronze-fg': 'var(--dt-bronze-fg)',
        'dt-silver-bg': 'var(--dt-silver-bg)', 'dt-silver-fg': 'var(--dt-silver-fg)',
        'dt-gold-bg': 'var(--dt-gold-bg)', 'dt-gold-fg': 'var(--dt-gold-fg)',
        'dt-platinum-bg': 'var(--dt-platinum-bg)', 'dt-platinum-fg': 'var(--dt-platinum-fg)',
        'dt-diamond-bg': 'var(--dt-diamond-bg)', 'dt-diamond-fg': 'var(--dt-diamond-fg)',
        'dt-master-bg': 'var(--dt-master-bg)', 'dt-master-fg': 'var(--dt-master-fg)',
      },
      borderRadius: {
        'dt-sm': 'var(--dt-radius-sm)',
        dt: 'var(--dt-radius)',
        'dt-md': 'var(--dt-radius-md)',
        'dt-pill': 'var(--dt-radius-pill)',
      },
      boxShadow: {
        'dt-card': 'var(--dt-card-shadow)',
      },
      fontFamily: {
        'dt-display': 'var(--dt-font-display)',
        'dt-sans': 'var(--dt-font-sans)',
        'dt-mono': 'var(--dt-font-mono)',
      },
      spacing: {
        'dt-xs': 'var(--dt-s-xs)',
        'dt-sm': 'var(--dt-s-sm)',
        'dt-md': 'var(--dt-s-md)',
        'dt-lg': 'var(--dt-s-lg)',
        'dt-xl': 'var(--dt-s-xl)',
        'dt-2xl': 'var(--dt-s-2xl)',
        'dt-3xl': 'var(--dt-s-3xl)',
      },
    },
  },
  plugins: [],
}

